apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-client-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-client
      client: "client-3"
  template:
    metadata:
      labels:
        app: redis-client
        client: "client-3"
    spec:
      containers:
      - name: redis-client
        image: redis:6.0
        command: ["sleep", "infinity"]
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: client-config
              key: redis_host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: client-config
              key: redis_port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        resources:
          requests:
            cpu: "0.2"
            memory: "256Mi"
          limits:
            cpu: "0.5"
            memory: "512Mi"