apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-0
  template:
    metadata:
      labels:
        app: client-0
    spec:
      containers:
      - name: client
        image: camilaapa/tp2-cluster-sync-redis:latest
        imagePullPolicy: Never
        env:
        - name: CLIENT_ID
          value: "client-0"
        - name: NODE_URL
          value: "http://node-0.node:5000"
        command: ["python", "client.py"]