apiVersion: batch/v1
kind: Job
metadata:
  name: client-0
spec:
  template:
    metadata:
      labels:
        app: client-0
    spec:
      restartPolicy: Never
      containers:
      - name: client
        image: camilaapa/tp2-cluster-sync-redis:latest
        imagePullPolicy: Never
        env:
        - name: CLIENT_ID
          value: "client-0"
        - name: NODE_URL
          value: "http://node-0.node:5000"
        command: ["python", "client.py"]