apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node
spec:
  serviceName: "node"
  replicas: 5
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: cluster-node
        image: camilaapa/tp2-cluster-sync-redis:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_SENTINELS
          value: "redis-sentinel:26379"
        - name: REDIS_SENTINEL_MASTER
          value: "mymaster"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command: ["python"]
        args: ["node.py"]
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 2